services:
  api:
    container_name: computer-use-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  ui:
    container_name: computer-use-ui
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    env_file:
      - .env
