name: computer-use
services:
  ui:
    container_name: computer-use-ui
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./computer_use:/home/computeruse/computer_use
      - ./image:/home/computeruse/image
      - ./.env:/home/computeruse/.env

  api:
    container_name: computer-use-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./computer_use:/home/computeruse/computer_use
      - ./image:/home/computeruse
      - ./.env:/home/computeruse/.env
